### ISSUE TITLE
Server bar back on the left side with icons rotated 90° clockwise.

### ISSUE THREAD

**Issue by Benji7010** [DiscordStyles/HorizontalServerList#82]
### Describe the bug
Title: Server bar back on the left side with icons rotated 90° clockwise.
I'm guessing discord update changing the markup.

### To Reproduce  
Use the theme. Has been replicated with settings file removed in case that mattered.

### Screenshots
<img width="1920" height="1032" alt="Image" src="https://github.com/user-attachments/assets/6b0a1860-6b77-46a2-aa8d-4a12d93dfd27" />

### Infomation
**Discord channel**: Stable
**OS**: Windows
**Mod**: Vencord 
**Discord language**: English

### Additional context
Probably discord changing things per the usual.

**Comment by Oroborius** [comment]
Can confirm is an issue and that @PoTPeM 's fix does work.

**Comment by LuxLauncher** [comment]
> > How do i change , so i can put the server list on the bottom?
> 
> I copied the values from the bottomhsl.css file into the above and it worked for me, here it is for easier copying:
> 
> ```
> overflow: visible !important;
> margin-top: unset;
> margin-bottom: var(--custom-guild-list-width);
> }
> 
> #app-mount .sidebar__5e434 {
> border-radius: 0;
> overflow: visible !important;
> }
> #app-mount .guilds__5e434 {
> transform-origin: top left;
> rotate: -90deg;
> height: 100vw !important;
> bottom: unset;
> position: absolute !important;
> left: 0;
> top: calc(100% + var(--custom-guild-list-width));
> }
> #app-mount .tree_ef3116 {
> padding-top: var(--HSL-top-padding, var(--size-sm));
> }
> #app-mount .wrapper_cc5dd2 {
> rotate: 90deg;
> }
> #app-mount .itemsContainer_ef3116,
> #app-mount .stack_dbd263 {
> flex-direction: var(--HSL-server-direction);
> justify-content: var(--HSL-server-alignment);
> }
> 
> .container_c48ade > div[style]:not(.base_c48ade) {
> width: 100vw !important;
> height: var(--custom-guild-list-width) !important;
> position: absolute;
> pointer-events: none;
> z-index: 1;
> bottom: calc(var(--custom-guild-list-width) * 2);
> top: unset;
> }
> .container_c48ade > div[style]:not(.base_c48ade) .guilds_c48ade {
> pointer-events: all;
> top: calc(100% + var(--custom-guild-list-width) * 2) !important;
> }
> .container_c48ade > div[style]:not(.base_c48ade) + .base_c48ade .content__5e434 {
> margin-top: unset;
> margin-bottom: calc(var(--custom-guild-list-width) * 2);
> }
> 
> :root {
> --HSL-server-direction: column; /* Direction of the server list. | OPTIONS: column, column-reverse | DEFAULT: column /
> --HSL-server-alignment: flex-start; / Alignment of the server list. | OPTIONS: flex-start, center, flex-end | DEFAULT: flex-start */
> }```
> ```

This has not worked for me, infact all it did was entirely remove the servers list

**Comment by LuxLauncher** [comment]
> > > > How do i change , so i can put the server list on the bottom?
> > > 
> > > 
> > > I copied the values from the bottomhsl.css file into the above and it worked for me, here it is for easier copying:
> > > ```
> > > overflow: visible !important;
> > > margin-top: unset;
> > > margin-bottom: var(--custom-guild-list-width);
> > > }
> > > 
> > > #app-mount .sidebar__5e434 {
> > > border-radius: 0;
> > > overflow: visible !important;
> > > }
> > > #app-mount .guilds__5e434 {
> > > transform-origin: top left;
> > > rotate: -90deg;
> > > height: 100vw !important;
> > > bottom: unset;
> > > position: absolute !important;
> > > left: 0;
> > > top: calc(100% + var(--custom-guild-list-width));
> > > }
> > > #app-mount .tree_ef3116 {
> > > padding-top: var(--HSL-top-padding, var(--size-sm));
> > > }
> > > #app-mount .wrapper_cc5dd2 {
> > > rotate: 90deg;
> > > }
> > > #app-mount .itemsContainer_ef3116,
> > > #app-mount .stack_dbd263 {
> > > flex-direction: var(--HSL-server-direction);
> > > justify-content: var(--HSL-server-alignment);
> > > }
> > > 
> > > .container_c48ade > div[style]:not(.base_c48ade) {
> > > width: 100vw !important;
> > > height: var(--custom-guild-list-width) !important;
> > > position: absolute;
> > > pointer-events: none;
> > > z-index: 1;
> > > bottom: calc(var(--custom-guild-list-width) * 2);
> > > top: unset;
> > > }
> > > .container_c48ade > div[style]:not(.base_c48ade) .guilds_c48ade {
> > > pointer-events: all;
> > > top: calc(100% + var(--custom-guild-list-width) * 2) !important;
> > > }
> > > .container_c48ade > div[style]:not(.base_c48ade) + .base_c48ade .content__5e434 {
> > > margin-top: unset;
> > > margin-bottom: calc(var(--custom-guild-list-width) * 2);
> > > }
> > > 
> > > :root {
> > > --HSL-server-direction: column; /* Direction of the server list. | OPTIONS: column, column-reverse | DEFAULT: column /
> > > --HSL-server-alignment: flex-start; / Alignment of the server list. | OPTIONS: flex-start, center, flex-end | DEFAULT: flex-start */
> > > }```
> > > ```
> > 
> > 
> > This has not worked for me, infact all it did was entirely remove the servers list
> 
> just use the one from [@PoTPeM](https://github.com/PoTPeM) like below
> 
> > ```
> > .content__5e434 {
> > margin-top: var(--custom-guild-list-width);
> > overflow: visible !important;
> > }
> > 
> > #app-mount .sidebar__5e434 {
> > border-radius: 0;
> > overflow: visible !important;
> > }
> > #app-mount .guilds__5e434 {
> > transform-origin: top left;
> > rotate: -90deg;
> > height: 100vw !important;
> > bottom: unset;
> > position: absolute !important;
> > left: 0;
> > }
> > #app-mount .tree_ef3116 {
> > padding-top: var(--HSL-top-padding, var(--size-sm));
> > }
> > #app-mount .wrapper_cc5dd2 {
> > rotate: 90deg;
> > }
> > #app-mount .itemsContainer_ef3116,
> > #app-mount .stack_dbd263 {
> > flex-direction: var(--HSL-server-direction);
> > justify-content: var(--HSL-server-alignment);
> > }
> > 
> > .container_c48ade > div[style]:not(.base_c48ade) {
> > width: 100vw !important;
> > height: var(--custom-guild-list-width) !important;
> > position: absolute;
> > top: calc(var(--custom-guild-list-width) + var(--custom-app-top-bar-height));
> > pointer-events: none;
> > z-index: 1;
> > }
> > .container_c48ade > div[style]:not(.base_c48ade) .guilds_c48ade {
> > pointer-events: all;
> > }
> > .container_c48ade > div[style]:not(.base_c48ade) + .base_c48ade .content__5e434 {
> > margin-top: calc(var(--custom-guild-list-width) * 2);
> > }
> > 
> > :root {
> > --HSL-server-direction: column; /* Direction of the server list. | OPTIONS: column, column-reverse | DEFAULT: column /
> > --HSL-server-alignment: flex-start; / Alignment of the server list. | OPTIONS: flex-start, center, flex-end | DEFAULT: flex-start */
> > }
> > ```

sure i could, but i do not like it on the top. i prefer it on the botton and i rather not use it if its on the top

**Comment by LuxLauncher** [comment]
just drag the boarder

**Comment by Gibbu** [comment]
Should be fixed now?

**Comment by DendrobiumBlossom** [comment]
This is an issue again as of the latest discord update.

**Comment by DendrobiumBlossom** [comment]
> > This is an issue again as of the latest discord update.
> 
> seems like another class change, along with some other changes
> 
> `_cc5dd2 -> __6e9f8`
> 
> ```
> #app-mount .wrapper__6e9f8,.folderPreviewWrapper__48112,.folderIcon__48112,.upperBadge_cc5dd2 {
>   rotate: 90deg;
> }
> ```
> 
> seems to fix it all
> 
> before
> <img alt="Image" width="374" height="55" src="https://private-user-images.githubusercontent.com/98378644/524995639-cb38f9b0-93d3-4633-abd1-aa04420f8d82.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUzOTU2OTAsIm5iZiI6MTc2NTM5NTM5MCwicGF0aCI6Ii85ODM3ODY0NC81MjQ5OTU2MzktY2IzOGY5YjAtOTNkMy00NjMzLWFiZDEtYWEwNDQyMGY4ZDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEwVDE5MzYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNmVlZGNjZmVjOTkyZGEyYzAzMjQ5M2IwNWRkZjI3ZWFiNWQyNGQ2ZjZkNTc4MTkzMDEwODA1OTE1NDQwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ISY7uW7b4S9GwHdk3LTWIHgCBwmT9vH4ilnF7A_1dhk"> <img alt="Image" width="134" height="47" src="https://private-user-images.githubusercontent.com/98378644/525000320-2ea27913-5641-4b24-9172-f467ea884ea3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUzOTU2OTAsIm5iZiI6MTc2NTM5NTM5MCwicGF0aCI6Ii85ODM3ODY0NC81MjUwMDAzMjAtMmVhMjc5MTMtNTY0MS00YjI0LTkxNzItZjQ2N2VhODg0ZWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEwVDE5MzYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlOTIxZTY4YmZmYjUxYzFjN2E4OWZlMWJlZDZkYTEyYzNkODMyNGYwMDA3MGRiZmFiNTExYjVhMmIzMDkyZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1v9qE7cd0lh_dg3DnT9P0v-dYP-FgXyn9ihSvZ1gA-s">
> 
> after
> <img alt="Image" width="409" height="57" src="https://private-user-images.githubusercontent.com/98378644/524995798-37190599-9366-4105-8259-489a8a44d200.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUzOTU2OTAsIm5iZiI6MTc2NTM5NTM5MCwicGF0aCI6Ii85ODM3ODY0NC81MjQ5OTU3OTgtMzcxOTA1OTktOTM2Ni00MTA1LTgyNTktNDg5YThhNDRkMjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEwVDE5MzYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTZjZjZjOGU5NmQzM2Q2ODA1N2UwOWRhY2E3ZDJkNjY5ZTg1MzBjZmQwYzA2MmJjZWQ3OTM0YjQzNDA1OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zyY8k4vtLaKIMXdUqEx56R4cOzb79sh6WPJWxnOGg_c"> <img alt="Image" width="143" height="46" src="https://private-user-images.githubusercontent.com/98378644/525000347-0df79a34-b195-4d66-afa5-813d287fa18a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUzOTU2OTAsIm5iZiI6MTc2NTM5NTM5MCwicGF0aCI6Ii85ODM3ODY0NC81MjUwMDAzNDctMGRmNzlhMzQtYjE5NS00ZDY2LWFmYTUtODEzZDI4N2ZhMThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEwVDE5MzYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNTRmMGQ2MmM1YzNkYmUzMjc5MGNlNjM1ZGNhNzA2MDYzNjQzODU0OGUzNjY0NWM2MDQzODM4YzExMzIzYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sHbvKVX2gE5VE0DM-WCm-clBvYgChftm73srx1ndHIY">
> 
> i am on vencord however and i can't seem to get the readall buttons to show up, probably nothing i can do on my side

Odd, I had to increase the rotation to 270 degrees, for my icons to be correct. Otherwise, it works.

**Comment by itachigoal** [comment]
> > > This is an issue again as of the latest discord update.
> > 
> > 
> > seems like another class change, along with some other changes
> > `_cc5dd2 -> __6e9f8`
> > ```
> > #app-mount .wrapper__6e9f8,.folderPreviewWrapper__48112,.folderIcon__48112,.upperBadge_cc5dd2 {
> >   rotate: 90deg;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > seems to fix it all
> > before
> > <img alt="Image" width="374" height="55" src="https://private-user-images.githubusercontent.com/98378644/524995639-cb38f9b0-93d3-4633-abd1-aa04420f8d82.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUzOTU2OTAsIm5iZiI6MTc2NTM5NTM5MCwicGF0aCI6Ii85ODM3ODY0NC81MjQ5OTU2MzktY2IzOGY5YjAtOTNkMy00NjMzLWFiZDEtYWEwNDQyMGY4ZDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEwVDE5MzYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNmVlZGNjZmVjOTkyZGEyYzAzMjQ5M2IwNWRkZjI3ZWFiNWQyNGQ2ZjZkNTc4MTkzMDEwODA1OTE1NDQwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ISY7uW7b4S9GwHdk3LTWIHgCBwmT9vH4ilnF7A_1dhk"> <img alt="Image" width="134" height="47" src="https://private-user-images.githubusercontent.com/98378644/525000320-2ea27913-5641-4b24-9172-f467ea884ea3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUzOTU2OTAsIm5iZiI6MTc2NTM5NTM5MCwicGF0aCI6Ii85ODM3ODY0NC81MjUwMDAzMjAtMmVhMjc5MTMtNTY0MS00YjI0LTkxNzItZjQ2N2VhODg0ZWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEwVDE5MzYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlOTIxZTY4YmZmYjUxYzFjN2E4OWZlMWJlZDZkYTEyYzNkODMyNGYwMDA3MGRiZmFiNTExYjVhMmIzMDkyZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1v9qE7cd0lh_dg3DnT9P0v-dYP-FgXyn9ihSvZ1gA-s">
> > after
> > <img alt="Image" width="409" height="57" src="https://private-user-images.githubusercontent.com/98378644/524995798-37190599-9366-4105-8259-489a8a44d200.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUzOTU2OTAsIm5iZiI6MTc2NTM5NTM5MCwicGF0aCI6Ii85ODM3ODY0NC81MjQ5OTU3OTgtMzcxOTA1OTktOTM2Ni00MTA1LTgyNTktNDg5YThhNDRkMjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEwVDE5MzYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTZjZjZjOGU5NmQzM2Q2ODA1N2UwOWRhY2E3ZDJkNjY5ZTg1MzBjZmQwYzA2MmJjZWQ3OTM0YjQzNDA1OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zyY8k4vtLaKIMXdUqEx56R4cOzb79sh6WPJWxnOGg_c"> <img alt="Image" width="143" height="46" src="https://private-user-images.githubusercontent.com/98378644/525000347-0df79a34-b195-4d66-afa5-813d287fa18a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUzOTU2OTAsIm5iZiI6MTc2NTM5NTM5MCwicGF0aCI6Ii85ODM3ODY0NC81MjUwMDAzNDctMGRmNzlhMzQtYjE5NS00ZDY2LWFmYTUtODEzZDI4N2ZhMThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEwVDE5MzYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNTRmMGQ2MmM1YzNkYmUzMjc5MGNlNjM1ZGNhNzA2MDYzNjQzODU0OGUzNjY0NWM2MDQzODM4YzExMzIzYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sHbvKVX2gE5VE0DM-WCm-clBvYgChftm73srx1ndHIY">
> > i am on vencord however and i can't seem to get the readall buttons to show up, probably nothing i can do on my side
> 
> Odd, I had to increase the rotation to 270 degrees, for my icons to be correct. Otherwise, it works.

Although I changed the code and all, but the discord icon and the folder icon is in the wrong way, as well as the folder contraction shows the server the same way as the discord and folder icon.

<img width="792" height="101" alt="Image" src="https://github.com/user-attachments/assets/ad9a7321-35ec-4cbb-8c85-9b6cd50e158d" />

<img width="578" height="132" alt="Image" src="https://github.com/user-attachments/assets/92bc982b-11dc-4f31-90e0-d41fdf8d3bdc" />

**Comment by itachigoal** [comment]
> > Although I changed the code and all, but the discord icon and the folder icon is in the wrong way, as well as the folder contraction shows the server the same way as the discord and folder icon.
> 
> it seems to work fine for me with no theme applied
> 
> <img alt="Image" width="243" height="45" src="https://private-user-images.githubusercontent.com/98378644/525014035-8551e630-a6cc-4a4f-8c9d-cbe47d7ea1ef.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUzOTY2ODUsIm5iZiI6MTc2NTM5NjM4NSwicGF0aCI6Ii85ODM3ODY0NC81MjUwMTQwMzUtODU1MWU2MzAtYTZjYy00YTRmLThjOWQtY2JlNDdkN2VhMWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEwVDE5NTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZTAwODVhZDE3OTYwODAzYTVjNzFkZmRjYTU0MWQ4NDhkM2Q1MGI1NGQ2ODdmOGYyMzk5ZjRmODU2Yjc3ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PxT6lCjVsEi-yqVwSNjP4IBR1uemreYdRGQvm6WGXrQ">
> here's my whole quick CSS snippet
> 
> ```
> .content__5e434 {
>   margin-top: var(--custom-guild-list-width);
>   overflow: visible !important;
> }
> :fullscreen .content__5e434 {
>   margin: 0 !important;
> }
> #app-mount .sidebar__5e434  {
>   border-radius: 0;
>   overflow: visible !important;
> }
> #app-mount .guilds__5e434 {
>   transform-origin: top left;
>   rotate: -90deg;
>   height: 100vw !important;
>   bottom: unset;
>   position: absolute !important;
>   left: 0;
> }
> #app-mount .tree_ef3116 {
>   padding-top: var(--HSL-top-padding, var(--size-sm));
> }
> #app-mount .wrapper__6e9f8,.folderPreviewWrapper__48112,.folderIcon__48112,.upperBadge_cc5dd2 {
>   rotate: 90deg;
> }
> 
> #app-mount .itemsContainer_ef3116,
> #app-mount .stack_dbd263 {
>   flex-direction: var(--HSL-server-direction);
>   justify-content: var(--HSL-server-alignment);
> }
> 
> 
> .container_c48ade > div[style]:not(.base_c48ade) {
>   width: 100vw !important;
>   height: var(--custom-guild-list-width) !important;
>   position: absolute;
>   top: calc(var(--custom-guild-list-width) + var(--custom-app-top-bar-height));
>   pointer-events: none;
>   z-index: 1;
> }
> .container_c48ade > div[style]:not(.base_c48ade) .guilds_c48ade {
>   pointer-events: all;
> }
> .container_c48ade > div[style]:not(.base_c48ade) + .base_c48ade .content__5e434 {
>   margin-top: calc(var(--custom-guild-list-width) * 2);
> }
> 
> 
> :root {
>   --HSL-server-direction: column; /* Direction of the server list. | OPTIONS: column, column-reverse | DEFAULT: column */
>   --HSL-server-alignment: flex-start; /* Alignment of the server list. | OPTIONS: flex-start, center, flex-end | DEFAULT: flex-start */
> }
> 
> [class*=avatardecoration i]{
>     display: none;
> }
> ```

I'll include my code, its literally the same as yours but the folder and the discord icon is still the same within the image I have included from the previous post.

```
.content__5e434 {
  margin-top: var(--custom-guild-list-width);
  overflow: visible !important;
}
:fullscreen .content__5e434 {
  margin: 0 !important;
}
#app-mount .sidebar__5e434  {
  border-radius: 0;
  overflow: visible !important;
}
#app-mount .guilds__5e434 {
  transform-origin: top left;
  rotate: -90deg;
  height: 100vw !important;
  bottom: unset;
  position: absolute !important;
  left: 0;
}
#app-mount .tree_ef3116 {
  padding-top: var(--HSL-top-padding, var(--size-sm));
}
#app-mount .wrapper__6e9f8,.folderPreviewWrapper__48112,.folderIcon__48112,.upperBadge_cc5dd2 {
  rotate: 270deg;
}

#app-mount .itemsContainer_ef3116,
#app-mount .stack_dbd263 {
  flex-direction: var(--HSL-server-direction);
  justify-content: var(--HSL-server-alignment);
}


.container_c48ade > div[style]:not(.base_c48ade) {
  width: 100vw !important;
  height: var(--custom-guild-list-width) !important;
  position: absolute;
  top: calc(var(--custom-guild-list-width) + var(--custom-app-top-bar-height));
  pointer-events: none;
  z-index: 1;
}
.container_c48ade > div[style]:not(.base_c48ade) .guilds_c48ade {
  pointer-events: all;
}
.container_c48ade > div[style]:not(.base_c48ade) + .base_c48ade .content__5e434 {
  margin-top: calc(var(--custom-guild-list-width) * 2);
}

:root {
  --HSL-server-direction: column; /* Direction of the server list. | OPTIONS: column, column-reverse | DEFAULT: column */
  --HSL-server-alignment: flex-start; /* Alignment of the server list. | OPTIONS: flex-start, center, flex-end | DEFAULT: flex-start */
  --HSL-server-width: 10px; /* Width of the server list. | OPTIONS: px, % | DEFAULT: 100% */
  --HSL-server-height: 10px; /* Height of the server list. | OPTIONS: px, % | DEFAULT: 50px */
  --HSL-server-gap: 30px; /* Gap between the servers. | OPTIONS: px, % | DEFAULT: 0px */
  --HSL-server-border-radius: 100px; /* Border radius of the server list. | OPTIONS: px, % | DEFAULT: 0px */
}
```

**Comment by PoTPeM** [comment]
> I'll include my code, its literally the same as yours but the folder and the discord icon is still the same within the image I have included from the previous post.


your code seems to work fine on my client as the same screen shot i posted, try disabling the theme you have and see if that fixes it

**Comment by PoTPeM** [comment]
> > > I'll include my code, its literally the same as yours but the folder and the discord icon is still the same within the image I have included from the previous post.
> > 
> > 
> > your code seems to work fine on my client as the same screen shot i posted, try disabling the theme you have and see if that fixes it
> 
> Didn't do anything to it lol, its the same thing in the screenshots I have included.

a bunch of other things seemed to be still be broken as well like vc icon postion and notifs, give me a bit

**Comment by TheSolenOne** [comment]
> > try to add these lines of code to your original theme file, works for me
> > #app-mount .wrapper__6e9f8{ rotate: 270deg; } #app-mount .tutorialContainer__1f388{ rotate: 90deg; }
> 
> <img alt="Image" width="468" height="66" src="https://private-user-images.githubusercontent.com/247230538/526279641-ec7bc9c5-bb8f-43ae-bc4e-c4174bc6c471.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU3NDA5MjYsIm5iZiI6MTc2NTc0MDYyNiwicGF0aCI6Ii8yNDcyMzA1MzgvNTI2Mjc5NjQxLWVjN2JjOWM1LWJiOGYtNDNhZS1iYzRlLWM0MTc0YmM2YzQ3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIxNFQxOTMwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTFkZDAyZmM2ZDcxZGViNjQ0N2Y3YTE3Mzg0YjY4MDMwYzA0M2EyNjQzYTI1NjdmODBlOWFiOGFmY2QyZjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3AUdhuYEaCIYN9_jTVv5LtpObBIAzJijL2j-CnmvajI">
> everything else is fixed, but the notif number is rotated 90deg as well.

I'm too lazy to fix this thing right now tbh, maybe I'll do it later

**Comment by TheSolenOne** [comment]
> Fixed but the notis are still on the side
> 
> <img alt="Image" width="96" height="49" src="https://private-user-images.githubusercontent.com/225652309/527499157-0e6da72d-e7a6-44f6-9d86-49130b9b45d9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU5OTU1MjcsIm5iZiI6MTc2NTk5NTIyNywicGF0aCI6Ii8yMjU2NTIzMDkvNTI3NDk5MTU3LTBlNmRhNzJkLWU3YTYtNDRmNi05ZDg2LTQ5MTMwYjliNDVkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIxN1QxODEzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWQyMTJmMWEzMjgxMGM1Y2FmODM1OTNjM2NjZWE0MjcxNTIxMjhmZjdlNTE1ODE4MTU5ZTY1M2NlMDZmZWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7vt0v_q_6Y4roHbluQSKL1NRh0t8IiyV4iWKDfVDCno">

.cc5dd25190031396-upperBadge, .cc5dd25190031396-lowerBadge{
rotate: 90deg;
}
